### PR TITLE
Updated the readme with yarn commands

### PR DESCRIPTION
**Pull request by VIPv6**
Updated the instructions with the yarn commands that worked for me when building the browser extension.  The NPM commands didn't work for me:

yarn install
yarn run build
yarn run package

### CODE REVIEW

**Comment by tasn** [comment]
Hey,

Thanks a lot for the PR! This will surely make it easier for yarn users to use this extension. Just one comment: I think many people still use npm, so could you please change the PR to include both?
So it'd say for example:

"You can either use `yarn` or `npm` to build this extension and instructions for both are included below"

and then

`npm install`
or
`yarn install`

for each section? Take a look at how other JS projects do it for reference...

Thanks again.

**Comment by VIPv6** [comment]
Actually, Tom.  the npm commands didn’t work at all for me.  Some research on the package.json and the web pack.config.js led me to yarn, which worked.  I think that only the yarn commands are relevant the way it currently stands.

Kevin

**Comment by tasn** [comment]
It's because it's meant to be `npm run-script build` and `npm run-script package`. Could you fix that as well and show the alternatives? If not, I'm happy to do that, but you'll have to rebase this patch over my changes.

**Comment by VIPv6** [comment]
Feel free to make the changes you like and I’ll rebase and do another pull request.  That should be cleaner.

**Comment by tasn** [comment]
Done, thanks!

**Comment by VIPv6** [comment]
I’m sorry, Tom.  I can’t figure out how to do a rebase.  I found the button in SourceTree, but I asks me to select a commit and doesn’t allow me to select a commit.  I can’t find the rebase option at Github.com.  I’m not willing to get into the command line for something this insignificant.  it’s crazy that it’s this difficult for such a tiny correction. — Kevin

**Comment by tasn** [comment]
OK, sorry to hear. Please let me know if you ever get around to it, happy to accept the patch as discussed above. Though at least we now got the readme to show the correct commands. Thanks for that.

**Pull request closed without merging**
